### ISSUE TITLE
[Bug] i can't open NomNom.exe

### ISSUE THREAD

**Issue by Syntax-Anonymous** [cengelha/NomNom#68]
Windows Version
Microsoft Windows 10 Enterprise 64-bit (Build 19043)

.NET Framework Version
4.8

Path

Save

Output

Game Platform
Unknown

Exception

Type
System.Windows.Markup.XamlParseException

Message
The invocation of the constructor on type 'NomNom.ViewModel.MainViewModel' that matches the specified binding constraints threw an exception.

Source
PresentationFramework

Stack Trace
at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
at System.Windows.Application.DoStartup()
at System.Windows.Application.<.ctor>b__1_0(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

InnerException

Type
System.AggregateException

Message
One or more errors occurred.

Source
mscorlib

Stack Trace
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
at NomNom.IO.IPlatform.BuildContainerCollection()
at NomNom.IO.PlatformFactory.GetPlatform(PlatformEnum platformEnum, String path, String& relocated)
at NomNom.IO.PlatformFactory.GetPlatform(String path, String& relocated)
at NomNom.Manager.SetSavePath(String path)
at NomNom.Manager.Initialize()
at NomNom.ViewModel.MainViewModel..ctor()

InnerException

Type
System.ArgumentOutOfRangeException

Message
Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

Source
mscorlib

Stack Trace
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at NomNom.IO.PlatformSteam.DecryptMeta(Container container, Byte[] meta)
at NomNom.IO.IPlatform.LoadMeta(Container container)
at NomNom.IO.PlatformSteam.LoadContainer(Container container)
at NomNom.IO.IPlatform.BuildContainer(Int32 index, Container container, Object data)
at NomNom.IO.IPlatform.<>c__DisplayClass89_1.<BuildContainerCollection>b__1()
at System.Threading.Tasks.Task.Execute()

**Comment by angelobarandino** [comment]
It was working before, now I can no longer open NomNom.exe

System.ArgumentException

An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NomNom.IO.PlatformMicrosoft.ReadMicrosoftContainer()
   at NomNom.IO.PlatformMicrosoft.BuildContainerCollection()
   at NomNom.IO.PlatformMicrosoft..ctor(String path)
   at NomNom.IO.PlatformFactory.GetPlatform(PlatformEnum platformEnum, String path, String& relocated)
   at NomNom.IO.PlatformFactory.GetPlatform(String path, String& relocated)
   at NomNom.Manager.SetSavePath(String path)
   at NomNom.Manager.Initialize()
   at NomNom.ViewModel.MainViewModel..ctor()

**Comment by Syntax-Anonymous** [comment]
i find the problem it was a path no man's sky "C:\Users\%UserName%\AppData\Roaming\Hello"
that's why it could not open "NomNom.exe"

**Comment by cengelha** [comment]
Please check and let me know if the issue persists in the latest version (3.7.0.20).

**Comment by rosinante666** [comment]
I am still seeing this in 3.7.0.20.


NomNom 3.7.0.20-alpha.20 Crash Report

Windows Version

Microsoft Windows 10 Pro for Workstations 64-bit (Build 19043)

.NET Framework Version

4.8

Path

Save


Output


Game Platform

Unknown

Exception

Type

System.Windows.Markup.XamlParseException

Message

The invocation of the constructor on type 'NomNom.ViewModel.MainViewModel' that matches the specified binding constraints threw an exception.

Source

PresentationFramework

Stack Trace

at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
at System.Windows.Application.DoStartup()
at System.Windows.Application.<.ctor>b__1_0(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

InnerException

Type

System.AggregateException

Message

One or more errors occurred.

Source

mscorlib

Stack Trace

at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
at NomNom.IO.IPlatform.BuildContainerCollection()
at NomNom.IO.PlatformFactory.GetPlatform(PlatformEnum platformEnum, String path, String& relocated)
at NomNom.IO.PlatformFactory.GetPlatform(String path, String& relocated)
at NomNom.Manager.SetSavePath(String path)
at NomNom.Manager.Initialize()
at NomNom.ViewModel.MainViewModel..ctor()

InnerException

Type

System.ArgumentOutOfRangeException

Message

Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

Source

mscorlib

Stack Trace

at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at NomNom.IO.PlatformSteam.DecompressData(Container container, Byte[] meta, Byte[] data)
at NomNom.IO.IPlatform.LoadData(Container container, Byte[] meta)
at NomNom.IO.IPlatform.BuildContainer(Int32 index, Container container, Object data)
at NomNom.IO.IPlatform.<>c__DisplayClass97_1.<BuildContainerCollection>b__1()
at System.Threading.Tasks.Task.Execute()

User Comment

Opening app
