### ISSUE TITLE
it keeps crashing  and im tryna use it for ps4 

### ISSUE THREAD

**Issue by jay1212124** [cengelha/NomNom#9]
Exception

Type
System.Windows.Markup.XamlParseException

Message
The invocation of the constructor on type 'NomNom.ViewModel.MainViewModel' that matches the specified binding constraints threw an exception.

Source
PresentationFramework

Stack Trace
at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
at System.Windows.Application.DoStartup()
at System.Windows.Application.<.ctor>b__1_0(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

InnerException

Type
System.ArgumentException

Message
The path is not of a legal form.

Source
mscorlib

Stack Trace
at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
at System.IO.Path.GetFullPathInternal(String path)
at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
at NomNom.IO.IPlatform.RelocatePath(String path) in C:\Users\cenge\source\repos\NomNom\NomNom\IO\IPlatform.cs:line 344
at NomNom.IO.IPlatform..ctor(String path) in C:\Users\cenge\source\repos\NomNom\NomNom\IO\IPlatform.cs:line 121
at NomNom.IO.PlatformFactory.GetPlatform(PlatformEnum platformEnum, String path, String& relocated) in C:\Users\cenge\source\repos\NomNom\NomNom\IO\PlatformFactory.cs:line 40
at NomNom.IO.PlatformFactory.GetPlatform(String path, String& relocated) in C:\Users\cenge\source\repos\NomNom\NomNom\IO\PlatformFactory.cs:line 22
at NomNom.Manager.SetSavePath(String path) in C:\Users\cenge\source\repos\NomNom\NomNom\Manager.cs:line 221
at NomNom.Manager.Initialize() in C:\Users\cenge\source\repos\NomNom\NomNom\Manager.cs:line 215
at NomNom.ViewModel.MainViewModel..ctor() in C:\Users\cenge\source\repos\NomNom\NomNom\ViewModel\MainViewModel.cs:line 226

**Comment by cengelha** [comment]
Thanks for reporting! 
I think I found the problem, but can you post the full path you are using? Or does it keep crashing even before you can do something?

**Comment by jay1212124** [comment]
it keeps crashing before i can even do anything

**Comment by jay1212124** [comment]
is there anything i can do to fix it

**Comment by cengelha** [comment]
Not really. But I can send you a dev build when I stabilized the current work to see if the change I wrote above about fixes it.

**Comment by jay1212124** [comment]
sure

**Comment by jay1212124** [comment]
eta when it should be stable
